base_version: 1.0
version: {base_version}.{build}

before_build:
  nuget restore src/BrowningStyle.sln

build:
  parallel: true
  project: src/BrowningStyle.sln
  publish_nuget: true
  publish_nuget_symbols: true

platform: Any CPU
configuration: Release

assembly_info:
  patch: true
  file: Version.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}.{build}'
  assembly_informational_version: '{version}'

deploy:
  - provider: GitHub
    artifact: /.*BrowningStyle\.dll/
    draft: false
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: false