install:
  - git remote set-url origin https://github.com/%APPVEYOR_REPO_NAME%.git

before_build:
  - nuget restore src\Wrench.sln
  - set OutDir=%APPVEYOR_BUILD_FOLDER%\bin
  - set IntermediateDir=%APPVEYOR_BUILD_FOLDER%\obj

platform: Any CPU
configuration: Release

build:
  parallel: true
  project: src\Wrench.sln

after_build:
  - 7z a -tzip Wrench.Source.%GitVersion_NuGetVersion%.zip src appveyor.yml
  - 7z a -tzip Wrench.Binaries.%GitVersion_NuGetVersion%.zip %OutDir%
  - nuget pack src\Wrench\Wrench.nuspec -BasePath src\Wrench -Properties version=%GitVersion_NuGetVersion%;outdir=%OutDir%\%configuration%

artifacts:
 - path: Wrench*.nupkg
   name: NuGet
 - path: Wrench.Binaries*.zip
   name: Binaries
 - path: Wrench.Source*.zip
   name: Source

deploy:
  - provider: GitHub
    release: v$(GitVersion_NuGetVersion)
    auth_token:
      #bsbuild 2014-12-31
      secure: Rzc/Lpf+X3hUpQhDyqHtELOsVmimpDOEgHkFeCl2KRl0lP5jxwUAftsDMrkmOYyH
    artifact: NuGet,Binaries
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: true

deploy:
  - provider: NuGet
    server: https://www.nuget.org
    api_key:
      #bdhess 2015-01-14
      secure: +o5S8m7NSWLOFM5hyIhrD+aHdZU2dLn83nCV3zIFV55OMNl5H8q2yRFsFzMMcOWn
    skip_symbols: true
    artifact: NuGet
    on:
      appveyor_repo_tag: true
