# Update assembly_version below if updating this!
version: 1.0.{build}

assembly_info:
  patch: true
  file: src\Properties\AssemblyInfo.cs
  assembly_version: '1.0'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
  nuget restore src\BrowningStyle.sln

platform: Any CPU
configuration: Release
environment:
  RunCodeAnalysis: true

build:
  parallel: true
  project: src\BrowningStyle.sln

after_build:
  nuget pack src\BrowningStyle.MSBuild.nuspec -Properties version=%APPVEYOR_BUILD_VERSION%;configuration=%CONFIGURATION%
  7z a -tzip -o.. BrowningStyle_%APPVEYOR_BUILD_VERSION%_Source.zip src appveyor.yml
  7z a -tzip -o.. BrowningStyle_%APPVEYOR_BUILD_VERSION%_Binaries.zip src\bin\%CONFIGURATION%\BrowningStyle.dll src\bin\%CONFIGURATION%\BrowningStyle.pdb

artifacts:
 - path: BrowningStyle.MSBuild*.nupkg
   name: NuGet Package
 - path: ..\BrowningStyle_$(appveyor_build_version)_Binaries.zip
   name: Binaries
 - path: ..\BrowningStyle_$(appveyor_build_version)_Source.zip
   name: Source

deploy:
  - provider: GitHub
    release: browningstyle v$(appveyor_build_version)
    auth_token:
      #bsbuild 2014-12-31
      secure: Rzc/Lpf+X3hUpQhDyqHtELOsVmimpDOEgHkFeCl2KRl0lP5jxwUAftsDMrkmOYyH
    artifact: Binaries,NuGet Package
    draft: false
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: false