# Update assembly_version below if updating this!
version: 1.0.{build}

assembly_info:
  patch: true
  file: Version.cs
  assembly_version: '1.0'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
  nuget restore src\BrowningStyle.sln

after_build:
  nuget pack src\BrowningStyle.MSBuild.nuspec -Properties version=$(version);configuration=$(configuration)

platform: Any CPU
configuration: Release
environment:
  RunCodeAnalysis: true

build:
  parallel: true
  project: src\BrowningStyle.sln
  publish_nuget: true
  publish_nuget_symbols: true

artifacts:
 - path: src\bin\$(configuration)\BrowningStyle.dll
   name: BrowningStyle.dll

deploy:
  - provider: GitHub
    release: browningstyle v$(version)
    auth_token:
      #bsbuild 2014-12-31
      secure: Rzc/Lpf+X3hUpQhDyqHtELOsVmimpDOEgHkFeCl2KRl0lP5jxwUAftsDMrkmOYyH
    artifact: /.*\.dll/
    draft: false
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: false