# Update assembly_version below if updating this!
version: 1.0.{build}

assembly_info:
  patch: true
  file: Version.cs
  assembly_version: '1.0'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
  nuget restore src/BrowningStyle.sln

build:
  parallel: true
  project: src/BrowningStyle.sln
  publish_nuget: true
  publish_nuget_symbols: true

platform: Any CPU
configuration: Release

deploy:
  - provider: GitHub
    artifact: /.*BrowningStyle\.dll/
    draft: false
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: false