version: ci-{build}

before_build:
  - git remote set-url origin https://github.com/%APPVEYOR_REPO_NAME%.git
  - gitversion .
  - nuget restore BrowningStyle\BrowningStyle.sln
  - 7z a -tzip BrowningStyle.Source.%GitVersion_NuGetVersion%.zip BrowningStyle appveyor.yml

platform: Any CPU
configuration: Release
environment:
  RunCodeAnalysis: true
  StyleCopTreatErrorsAsWarnings: false
  TreatWarningsAsErrors: true
  CodeAnalysisTreatWarningsAsErrors: true

build:
  parallel: true
  project: BrowningStyle\BrowningStyle.sln

after_build:
  - nuget pack BrowningStyle\src\BrowningStyle.MSBuild.nuspec -Properties version=%GitVersion_NuGetVersion%;configuration=%CONFIGURATION%
  - 7z a -tzip BrowningStyle.Binaries.%GitVersion_NuGetVersion%.zip .\BrowningStyle\src\bin\%CONFIGURATION%\BrowningStyle.dll .\BrowningStyle\src\bin\%FullSemVer%\BrowningStyle.pdb

artifacts:
 - path: BrowningStyle.MSBuild*.nupkg
   name: NuGet
 - path: BrowningStyle.Binaries*.zip
   name: Binaries
 - path: BrowningStyle.Source*.zip
   name: Source
 - path: logs
   name: Logs

deploy:
  - provider: GitHub
    release: v$(GitVersion_NuGetVersion)
    auth_token:
      #bsbuild 2014-12-31
      secure: Rzc/Lpf+X3hUpQhDyqHtELOsVmimpDOEgHkFeCl2KRl0lP5jxwUAftsDMrkmOYyH
    artifact: NuGet,Binaries
    draft: false
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: true
