install:
  - git remote set-url origin https://github.com/%APPVEYOR_REPO_NAME%.git

before_build:
  - nuget restore src\Wrench.sln
  - set OutDir=%APPVEYOR_BUILD_FOLDER%\bin
  - set IntermediateDir=%APPVEYOR_BUILD_FOLDER%\obj

platform: Any CPU
configuration: Release

build:
  parallel: true
  project: src\Wrench.sln

after_build:
  - 7z a -tzip Wrench.Source.%GitVersion_NuGetVersion%.zip src appveyor.yml
  - 7z a -tzip Wrench.Binaries.%GitVersion_NuGetVersion%.zip %OutDir%
  - nuget pack src\Wrench\Wrench.nuspec -BasePath src\Wrench -Properties version=%GitVersion_NuGetVersion%;outdir=%OutDir%\%configuration%

artifacts:
 - path: Wrench*.nupkg
   name: NuGet
 - path: Wrench.Binaries*.zip
   name: Binaries
 - path: Wrench.Source*.zip
   name: Source

deploy:
  - provider: GitHub
    release: v$(GitVersion_NuGetVersion)
    auth_token:
      #bdhess-bot 2015-04-13
      secure: xbPXf7huVM5TwkHbgC9L1vb5qe/7a5wlMqOrpArzXslYOfiUYTsjDCseoHSmPlhh
    artifact: NuGet,Binaries
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: true

  - provider: NuGet
    server: https://www.nuget.org
    api_key:
      #bdhess@live.com 2015-04-13
      secure: 82b5uCCj8Hx3qWNUX4LatNKcSsmvJ+HAkyBBn5wvJUQ0CZjsN4Il4RoTTRSDcFM1
    skip_symbols: true
    artifact: NuGet
    on:
      appveyor_repo_tag: true
