# Update assembly_version below if updating this!
version: 1.0.{build}

assembly_info:
  patch: true
  file: src\Properties\AssemblyInfo.cs
  assembly_version: '1.0'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
  nuget restore src\BrowningStyle.sln

after_build:
  nuget pack src\BrowningStyle.MSBuild.nuspec -Properties version=%APPVEYOR_BUILD_VERSION%;configuration=%CONFIGURATION%


platform: Any CPU
configuration: Release
environment:
  RunCodeAnalysis: true

build:
  parallel: true
  project: src\BrowningStyle.sln

artifacts:
 - path: BrowningStyle.MSBuild*.nupkg
   name: NuGet Package
 - path: src\bin\$(configuration)\BrowningStyle.dll,src\bin\$(configuration)\BrowningStyle.pdb
   name: Binaries
   type: zip
 - path: src,appveyor.yml
   name: Source
   type: zip

deploy:
  - provider: GitHub
    release: browningstyle v$(appveyor_build_version)
    auth_token:
      #bsbuild 2014-12-31
      secure: Rzc/Lpf+X3hUpQhDyqHtELOsVmimpDOEgHkFeCl2KRl0lP5jxwUAftsDMrkmOYyH
    artifact: Binaries,NuGet Package
    draft: false
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: false